#ifndef EXAMPLE_H_INCLUDED
#define EXAMPLE_H_INCLUDED

/* export macros for library generated by CMake */
#ifndef EXAMPLE_API
#include "example_export.h"
#define EXAMPLE_API EXAMPLE_EXPORT
#endif

#ifdef __cplusplus
extern "C" {
#endif

EXAMPLE_API
double *get_array_leaky(const int len);

EXAMPLE_API
void get_array_safe(const int len, double array[]);

#ifdef __cplusplus
}
#endif

#endif /* EXAMPLE_H_INCLUDED */
